author = 'Jam Risser'
copyright = '2019, Jam Risser'
exclude_patterns = []
extensions = []
html_static_path = ['_static']
html_theme = 'alabaster'
project = 'sphinxdoc'
release = '0.0.1'
templates_path = ['_templates']
